[project]
name = "min-cutrank"
version = "0.1.0"
description = "Efficient algorithm finding a bipartition with minimal cut-rank in graphs."
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
dependencies = [
    "numpy>=2.3.5",
]